//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.479.0.
namespace XSD
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.479.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("gunstore", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("gunstore", Namespace="")]
    public partial class Gunstore
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<GunstoreClassGun> _class;
        
        [System.Xml.Serialization.XmlArrayAttribute("class")]
        [System.Xml.Serialization.XmlArrayItemAttribute("gun")]
        public System.Collections.ObjectModel.Collection<GunstoreClassGun> Class
        {
            get
            { 
                return this._class;
            }
            private set
            {
                this._class = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Class-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Class collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassSpecified
        {
            get
            {
                return (this.Class.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Gunstore" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Gunstore" /> class.</para>
        /// </summary>
        public Gunstore()
        {
            this._class = new System.Collections.ObjectModel.Collection<GunstoreClassGun>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.479.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GunstoreClass", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GunstoreClass
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<GunstoreClassGun> _gun;
        
        [System.Xml.Serialization.XmlElementAttribute("gun")]
        public System.Collections.ObjectModel.Collection<GunstoreClassGun> Gun
        {
            get
            {
                return this._gun;
            }
            private set
            {
                this._gun = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Gun-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Gun collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GunSpecified
        {
            get
            {
                return (this.Gun.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="GunstoreClass" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GunstoreClass" /> class.</para>
        /// </summary>
        public GunstoreClass()
        {
            this._gun = new System.Collections.ObjectModel.Collection<GunstoreClassGun>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.479.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GunstoreClassGun", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GunstoreClassGun
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("year")]
        public string Year { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("price")]
        public float Price { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
    }
}
